### ISSUE TITLE
After topping up credits, songs still limited to 45 seconds

### ISSUE THREAD

**Issue by Fang-** [resonatecoop/resonate#22]
Songs started playing for only 45 seconds, and those plays were (correctly) not registering anymore. I had run out of credits.

After topping them up (pretty good flow (: ) I tried to continue playing, but could only get songs to play for 45 seconds still. Reload, re-login did nothing. Had to manually clear all cookies for resonate domains to get playback to happen normally again.

It _might_ have counted one of the 45-second plays after topping up as a full, paid playback, but not entirely sure of that.

**Comment by auggod** [comment]
Stream url for full and truncated tracks is the same. This leads to caching issues unfortunately... Having to handle two different urls is not nice, we would need to refetch current playlist and rerender everything. I'll figure out what's the best way to handle this problem.

**Comment by Fang-** [comment]
Naive suggestion: how about clearing cache on-fund?

**Comment by auggod** [comment]
I added a parameter preview=true|false to stream urls based on current credit amount. It should prevent caching problems. It won't work for a track currently playing, you'll have to play a different track first. This should be enough until we find a better way to handle this problem.
