### ISSUE TITLE
When playing from a list, stops on end of page

### ISSUE THREAD

**Issue by Fang-** [resonatecoop/resonate#24]
At least, this is what I'm experiencing when playing from `/playlist/latest`.

If you're playing the last song on the page, and it either finishes or you hit the "next song" button, it just stops playing.

Expected behavior here is to keep playing with songs on the next page. Instead, I have to manually move to the next page and start playback again.

**Comment by auggod** [comment]
I think it's time to have a proper queue system and UI. I'd like to have control over how many tracks to play in a row and those to skip. Should be easy enough to prefetch the next pages if playlist is about to reach the end.
