### ISSUE TITLE
Continuous play not working after screen is locked (iOS)

### ISSUE THREAD

**Issue by regisfrias** [resonatecoop/resonate#29]
### Operating system
iOS 12.4 (iPhone).

### Browser name and version
Safari 12.4, Firefox 18.1 (15719), Chrome 76.0.3809.81. (Probably OS-level issue?)

### Expected behavior
Continuous play.

### Actual behavior
When screen is locked the next song won't play. When the phone is unlocked the next song shows as playing (pause button is active), but not really playing. To resume play you need to hit pause then hit play again.

### Steps to reproduce behavior
Trigger a list play, then lock the screen.

**Comment by auggod** [comment]
Can you try changing Safari settings for autoplay? Autoplay might be prevented for safari and other browsers. I don't have an ios device with me to check that issue right now.

**Comment by regisfrias** [comment]
I guess I can't choose that myself.

https://bitmovin.com/play-not-play-new-autoplay-policies-safari-11-chrome-64/

This article mentions this, though:

```javascript
var promise = document.querySelector('video').play();
if (promise !== undefined) {
 promise.then(_ => {
   // Autoplay started!
 }).catch(error => {
   // Autoplay was prevented.
   // Show a "Play" button so that user can start playback.
 });
}
```

This should at least show the play button instead of pause as it is now when I reopen the screen.
