### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by Jake-Gillberg** [resonatecoop/resonate#5]
Hello! Recently began talking with Peter about analytics and the need for artist / label / content page views. I'd be happy to help out with this :)

Sounds like Matomo is what was being used before, and possibly what you would like to use here? Seems like this could be a potential way forward (adding an event listener looking for url changes): https://developer.matomo.org/guides/spa-tracking .

Another route would be to add tracking in the history stack ala ga url-change-tracker: https://github.com/googleanalytics/autotrack/blob/99f7c61b30553fecdd99187c83441579fe2b4064/lib/plugins/url-change-tracker.js .

**Comment by auggod** [comment]
With choo, we could do this:

```js

emitter.on(state.events.NAVIGATE, function() {
        _paq.push(['setCustomUrl', '/' + state.href]);
        _paq.push(['setDocumentTitle', state.title]);
        _paq.push(['trackPageView']);
});


```
