### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by tomkel** [resonatecoop/resonate#6]
Hello. Seeing as how this project hooks into nginx for prod, maybe it would be worth the effort to create a Dockerfile for this?

**Comment by auggod** [comment]
Yes, it would be easier for everyone and not only an improvement for production. We plan to do static deployments with `now.sh`. Docker won't be needed in that case. The current unknown for me is how to deal with lerna monorepo and now.sh to automate deployments from github to now.sh.
